version: '3.8'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    command: pytest tests/ -v --cov=app --cov-report=term-missing
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitcoin_prices_test
      - POSTGRES_HOST=test-db
      - POSTGRES_PORT=5432
      - REDIS_HOST=test-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - COINGECKO_API_URL=https://api.coingecko.com/api/v3
      - CURRENT_PRICE_CACHE_TTL=300
      - TESTING=true
    depends_on:
      test-db:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-migration:
        condition: service_completed_successfully

  test-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitcoin_prices_test
    ports:
      - "5434:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1g

  test-redis:
    image: redis:6
    ports:
      - "6381:6379"
    volumes:
      - test-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  test-migration:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    command: alembic upgrade head
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitcoin_prices_test
      - POSTGRES_HOST=test-db
      - POSTGRES_PORT=5432
    depends_on:
      test-db:
        condition: service_healthy

volumes:
  test-db-data:
  test-redis-data: 